import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MenuComponent from "./components/MenuComponent";
import locale from 'antd/locale/ru_RU';
import moment from 'moment';
import 'moment/locale/ru';
import { ConfigProvider } from "antd";
import { Footer } from "antd/es/layout/layout";
moment.locale("ru");

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Eventify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MenuComponent/>
        <ConfigProvider locale={locale}>
          {children}
        </ConfigProvider>
        <Footer style={{ textAlign: "center" }}>
          Event Management ©2024 Created by Dawnweave
        </Footer>
      </body>
    </html>
  );
}
